[package]
name = "HangMan2"
version = "0.1.0"
authors = ["Dylan <dylan_w2014@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-segmentation = "1.6.0"
rand = "0.7.3"